version: '3'
services:
  server:
    build: ./server
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
    ports:
      - '5000:5000'
    links:
      - mongo
    environment:
      - RUNNING_IN_DOCKER=true
  client:
    build: ./client
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/app
    ports:
      - '5173:5173'
  mongo:
    image: mongo
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - '27017:27017'