version: '3'
services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - '5000:5000'
    links:
      - mongo
    environment:
      - RUNNING_IN_DOCKER=true
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'